### ISSUE TITLE
Keyboard automatically closes

### ISSUE THREAD

**Issue by Fillix441** [nezort11/chatgpt-mobile#11]
After every character input the keyboard closes

**Comment by b3il0** [comment]
Maybe try clearing the apps cache, that helped me, although it can happen again. But I haven't had it for a very long time now.

**Comment by Fillix441** [comment]
The problem still persists.

**Comment by b3il0** [comment]
I'm sorry to hear, I'm not the developer, that's just my experience. Open a new chat after clearing the cache. And generally, as soon as this occurs, it sometimes helps if you simply open a new chat.

**Comment by Fillix441** [comment]
It worked. Thanks.
